Gemspec/RequiredRubyVersion:
  Include:
    - 'braintree.gemspec'

AllCops:
  DisabledByDefault: true
  TargetRubyVersion: 2.6
  SuggestExtensions: false

Layout/BlockAlignment:
  EnforcedStyleAlignWith: either

Layout/DotPosition:
  EnforcedStyle: leading

Layout/SpaceBeforeBlockBraces:
  EnforcedStyle: space

Layout/SpaceInsideBlockBraces:
  EnforcedStyle: space

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
  EnforcedStyleForEmptyBraces: no_space

Layout/SpaceInsideParens:
  EnforcedStyle: no_space

Layout/IndentationStyle:
  EnforcedStyle: spaces
  Enabled: true

Layout/TrailingWhitespace:
  Enabled: true

Lint/AmbiguousAssignment:
  Enabled: true

Lint/AmbiguousBlockAssociation:
  Enabled: true

Lint/AmbiguousOperator:
  Enabled: true

Lint/AmbiguousRegexpLiteral:
  Enabled: true

Lint/AssignmentInCondition:
  Enabled: true

Lint/BigDecimalNew:
  Enabled: true

Lint/BinaryOperatorWithIdenticalOperands:
  Enabled: true

Lint/BooleanSymbol:
  Enabled: true

Lint/CircularArgumentReference:
  Enabled: true

Lint/ConstantDefinitionInBlock:
  Enabled: true

# NEXT_MAJOR_VERSION add ConstantResolution rule and start changing all constants to
# SCREAMING_SNAKE_CASE
Lint/ConstantResolution:
  Enabled: false

Lint/Debugger:
  Enabled: true

Lint/DeprecatedClassMethods:
  Enabled: true

Lint/DeprecatedConstants:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/DisjunctiveAssignmentInConstructor:
  Enabled: true

Lint/DuplicateCaseCondition:
  Enabled: true

Lint/DuplicateElsifCondition:
  Enabled: true

Lint/DuplicateHashKey:
  Enabled: true

Lint/DuplicateMethods:
  Enabled: true

Lint/DuplicateRegexpCharacterClassElement:
  Enabled: true

Lint/DuplicateRequire:
  Enabled: true

Lint/DuplicateRescueException:
  Enabled: true

Lint/EachWithObjectArgument:
  Enabled: true

Lint/ElseLayout:
  Enabled: true

Lint/EmptyBlock:
  Enabled: true
  AllowComments: true
  Exclude:
  - spec/integration/braintree/document_upload_spec.rb

Lint/EmptyClass:
  Enabled: true

Lint/EmptyConditionalBody:
  Enabled: true

Lint/EmptyEnsure:
  Enabled: true

Lint/EmptyExpression:
  Enabled: true

Lint/EmptyFile:
  Enabled: true

Lint/EmptyInterpolation:
  Enabled: true

Lint/EmptyWhen:
  Enabled: true

Lint/EnsureReturn:
  Enabled: true

Lint/FlipFlop:
  Enabled: true

Lint/FloatComparison:
  Enabled: true

Lint/FloatOutOfRange:
  Enabled: true

Lint/FormatParameterMismatch:
  Enabled: true

Lint/HashCompareByIdentity:
  Enabled: true

Lint/HeredocMethodCallPosition:
  Enabled: true

Lint/IdentityComparison:
  Enabled: true

Lint/ImplicitStringConcatenation:
  Enabled: true

Lint/IneffectiveAccessModifier:
  Enabled: true

Lint/InheritException:
  Enabled: true

Lint/InterpolationCheck:
  Enabled: true

Lint/LambdaWithoutLiteralBlock:
  Enabled: true

Lint/LiteralAsCondition:
  Enabled: true

Lint/LiteralInInterpolation:
  Enabled: true

Lint/Loop:
  Enabled: true

Lint/MissingCopEnableDirective:
  Enabled: true

Lint/MultipleComparison:
  Enabled: true

Lint/NestedMethodDefinition:
  Enabled: true

Lint/NestedPercentLiteral:
  Enabled: true

Lint/NextWithoutAccumulator:
  Enabled: true

Lint/NonDeterministicRequireOrder:
  Enabled: true

Lint/NoReturnInBeginEndBlocks:
  Enabled: true

Lint/NonLocalExitFromIterator:
  Enabled: true

Lint/NumberedParameterAssignment:
  Enabled: true

Lint/OrAssignmentToConstant:
  Enabled: true

Lint/OrderedMagicComments:
  Enabled: true

Lint/OutOfRangeRegexpRef:
  Enabled: true

Lint/ParenthesesAsGroupedExpression:
  Enabled: true

Lint/PercentStringArray:
  Enabled: true

Lint/PercentSymbolArray:
  Enabled: true
  
Lint/RaiseException:
  Enabled: true

Lint/RandOne:
  Enabled: true

Lint/RedundantCopDisableDirective:
  Enabled: true

Lint/RedundantCopEnableDirective:
  Enabled: true

Lint/RedundantDirGlobSort:
  Enabled: true

Lint/RedundantRequireStatement:
  Enabled: true

Lint/RedundantSafeNavigation:
  Enabled: true

Lint/RedundantSplatExpansion:
  Enabled: true

Lint/RedundantStringCoercion:
  Enabled: true

Lint/RedundantWithIndex:
  Enabled: true

Lint/RedundantWithObject:
  Enabled: true

Lint/RegexpAsCondition:
  Enabled: true

Lint/RequireParentheses:
  Enabled: true

Lint/RescueException:
  Enabled: true

Lint/RescueType:
  Enabled: true

Lint/ReturnInVoidContext:
  Enabled: true

Lint/SafeNavigationChain:
  Enabled: true

Lint/SafeNavigationConsistency:
  Enabled: true

Lint/SafeNavigationWithEmpty:
  Enabled: true

Lint/ScriptPermission:
  Enabled: true

Lint/SelfAssignment:
  Enabled: true

Lint/SendWithMixinArgument:
  Enabled: true

Lint/ShadowedArgument:
  Enabled: true

Lint/ShadowedException:
  Enabled: true

Lint/ShadowingOuterLocalVariable:
  Enabled: true
  Exclude:
   - spec/**/*

Lint/StructNewOverride:
  Enabled: true

Lint/SuppressedException:
  Enabled: true
  AllowComments: true

Lint/SymbolConversion:
  Enabled: true

Lint/Syntax:
  Enabled: true

Lint/ToEnumArguments:
  Enabled: true

Lint/ToJSON:
  Enabled: true

Lint/TopLevelReturnWithArgument:
  Enabled: true

Lint/TrailingCommaInAttributeDeclaration:
  Enabled: true

Lint/TripleQuotes:
  Enabled: true

Lint/UnderscorePrefixedVariableName:
  Enabled: true

Lint/UnexpectedBlockArity:
  Enabled: true

Lint/UnifiedInteger:
  Enabled: true

Lint/UnmodifiedReduceAccumulator:
  Enabled: true

Lint/UnreachableCode:
  Enabled: true
  Exclude:
   - lib/braintree/xml/parser.rb

Lint/UnreachableLoop:
  Enabled: true

Lint/UnusedBlockArgument:
  Enabled: true

Lint/UriEscapeUnescape:
  Enabled: true

Lint/UriRegexp:
  Enabled: true

Lint/UselessAccessModifier:
  Enabled: true

Lint/UselessAssignment:
  Enabled: true

Lint/UselessElseWithoutRescue:
  Enabled: true

Lint/UselessMethodDefinition:
  Enabled: true

Lint/UselessSetterCall:
  Enabled: true

Lint/UselessTimes:
  Enabled: true

Lint/Void:
  Enabled: true
  Exclude:
   - spec/**/*

Style/DefWithParentheses:
  Enabled: true

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
